# iris config
DisablePathCorrection: false
EnablePathEscape: false
FireMethodNotAllowed: true
DisableBodyConsumptionOnUnmarshal: true
TimeFormat: Mon, 01 Jan 2006 15:04:05 GMT
Charset: UTF-8

# mysql数据库账号配置
mysql:
  user: root
  password: 123456   # 123456 ,  qw84265
  host: localhost    # localhost ,119.23.74.49
  port: 3306
  database: nuu_db
  charset: utf8

# redis账号配置
redis:
  password: null  # null ,nuu1234mobile
  host: localhost    # localhost ,119.23.74.49
  port: 6379

# platform config
url: http://47.91.250.107:80/api/public_intf
itf_name: query_device_package_info
trans_serial: 1234cde
login: tuser
auth_code: abcd456

# PayPal account
clientID: ASskKGQjRAf-6jAdwn771epAcx7C_dDNBGH-SMtjbo9xAlbV-D7Ah695YLTdllnRCPklUZdjjH1mlTcW
secretID: EHyzTazQP6MDA4vmW7mbhPdBiENmd3KO2aPjk-iEExbNIZ80ZNw177G8_-wxAEG8xHuyAklW9pSbKHUc
# 沙盒: https://api.sandbox.paypal.com
# 正式: https://api.paypal.com
APIBaseLive: https://api.sandbox.paypal.com

# platform api config
used_today_detail: query_device_package_info
package_sale: query_package_for_device
package_pay_done: buy_package
package_query: query_package
setup_wifi: device_wifi_setup
used_detail: query_used_package

# send email
smtp: smtp.exmail.qq.com
send_account: qius@edaceo.com
send_password: 1991ly2009